spring:
  application:
    name: eureka-service-single
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册到eureka service中去 默认为true
    register-with-eureka: false
    #表示是否从eureka service中获取注册信息 默认为true
    fetch-registry: false
    #与eureka service交互的地址，查询与注册都依赖它，默认端口8761 可以多个用,分割
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/